//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.InputAccel.UimScript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Custom.InputAccel.UimScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancelCaption {
            get {
                return ResourceManager.GetString("ButtonCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOkCaption {
            get {
                return ResourceManager.GetString("ButtonOkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor List.
        /// </summary>
        internal static string DialogVendorList_Title {
            get {
                return ResourceManager.GetString("DialogVendorList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string Label_InvoiceBox {
            get {
                return ResourceManager.GetString("Label_InvoiceBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        internal static string Label_InvoiceNum {
            get {
                return ResourceManager.GetString("Label_InvoiceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Type.
        /// </summary>
        internal static string Label_InvoiceType {
            get {
                return ResourceManager.GetString("Label_InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Type.
        /// </summary>
        internal static string Label_InvoiceTypeTooltip {
            get {
                return ResourceManager.GetString("Label_InvoiceTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Label_ItemAmount {
            get {
                return ResourceManager.GetString("Label_ItemAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Amount.
        /// </summary>
        internal static string Label_ItemAmountTooltip {
            get {
                return ResourceManager.GetString("Label_ItemAmountTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Count.
        /// </summary>
        internal static string Label_ItemCount {
            get {
                return ResourceManager.GetString("Label_ItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Count.
        /// </summary>
        internal static string Label_ItemCountTooltip {
            get {
                return ResourceManager.GetString("Label_ItemCountTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Label_ItemDescription {
            get {
                return ResourceManager.GetString("Label_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item description.
        /// </summary>
        internal static string Label_ItemDescriptionTooltip {
            get {
                return ResourceManager.GetString("Label_ItemDescriptionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Lookup.
        /// </summary>
        internal static string Label_SelectionLookup {
            get {
                return ResourceManager.GetString("Label_SelectionLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string Label_Shipping {
            get {
                return ResourceManager.GetString("Label_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string Label_ShippingTooltip {
            get {
                return ResourceManager.GetString("Label_ShippingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string Label_Subtotal {
            get {
                return ResourceManager.GetString("Label_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item amount subtotal.
        /// </summary>
        internal static string Label_SubtotalTooltip {
            get {
                return ResourceManager.GetString("Label_SubtotalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Label_Total {
            get {
                return ResourceManager.GetString("Label_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item amount total.
        /// </summary>
        internal static string Label_TotalTooltip {
            get {
                return ResourceManager.GetString("Label_TotalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Address.
        /// </summary>
        internal static string Label_VendorAddress {
            get {
                return ResourceManager.GetString("Label_VendorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Address.
        /// </summary>
        internal static string Label_VendorAddressTooltip {
            get {
                return ResourceManager.GetString("Label_VendorAddressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Information.
        /// </summary>
        internal static string Label_VendorBox {
            get {
                return ResourceManager.GetString("Label_VendorBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ID.
        /// </summary>
        internal static string Label_VendorID {
            get {
                return ResourceManager.GetString("Label_VendorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ID.
        /// </summary>
        internal static string Label_VendorIDTooltip {
            get {
                return ResourceManager.GetString("Label_VendorIDTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Vendor.
        /// </summary>
        internal static string Label_VendorLookup {
            get {
                return ResourceManager.GetString("Label_VendorLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Vendor button.
        /// </summary>
        internal static string Label_VendorLookupTooltip {
            get {
                return ResourceManager.GetString("Label_VendorLookupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        internal static string Label_VendorName {
            get {
                return ResourceManager.GetString("Label_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        internal static string Label_VendorNameTooltip {
            get {
                return ResourceManager.GetString("Label_VendorNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of item amounts {0} does not match to Subtotal amount {1}..
        /// </summary>
        internal static string RuleFailMessage_SubtotalSum {
            get {
                return ResourceManager.GetString("RuleFailMessage_SubtotalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor validation failed..
        /// </summary>
        internal static string RuleFailMessage_VendorValidation {
            get {
                return ResourceManager.GetString("RuleFailMessage_VendorValidation", resourceCulture);
            }
        }
    }
}
