//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Custom.InputAccel.UimScript.APISoap {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="captivaPortSoap11", Namespace="http://document.fwd.co.th/captiva")]
    public partial class captivaPortService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback uploadDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback completedExtractedDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback poppulateDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback generateSubmissionNumberOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public captivaPortService() {
            this.Url = global::Custom.InputAccel.UimScript.Properties.Settings.Default.Custom_InputAccel_UimScript_APISoap_captivaPortService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event uploadDocumentCompletedEventHandler uploadDocumentCompleted;
        
        /// <remarks/>
        public event completedExtractedDataCompletedEventHandler completedExtractedDataCompleted;
        
        /// <remarks/>
        public event poppulateDataCompletedEventHandler poppulateDataCompleted;
        
        /// <remarks/>
        public event generateSubmissionNumberCompletedEventHandler generateSubmissionNumberCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("uploadDocumentResponse", Namespace="http://document.fwd.co.th/captiva")]
        public uploadDocumentResponse uploadDocument([System.Xml.Serialization.XmlElementAttribute(Namespace="http://document.fwd.co.th/captiva")] uploadDocumentRequest uploadDocumentRequest) {
            object[] results = this.Invoke("uploadDocument", new object[] {
                        uploadDocumentRequest});
            return ((uploadDocumentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void uploadDocumentAsync(uploadDocumentRequest uploadDocumentRequest) {
            this.uploadDocumentAsync(uploadDocumentRequest, null);
        }
        
        /// <remarks/>
        public void uploadDocumentAsync(uploadDocumentRequest uploadDocumentRequest, object userState) {
            if ((this.uploadDocumentOperationCompleted == null)) {
                this.uploadDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadDocumentOperationCompleted);
            }
            this.InvokeAsync("uploadDocument", new object[] {
                        uploadDocumentRequest}, this.uploadDocumentOperationCompleted, userState);
        }
        
        private void OnuploadDocumentOperationCompleted(object arg) {
            if ((this.uploadDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadDocumentCompleted(this, new uploadDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("completedExtractedDataResponse", Namespace="http://document.fwd.co.th/captiva")]
        public completedExtractedDataResponse completedExtractedData([System.Xml.Serialization.XmlElementAttribute(Namespace="http://document.fwd.co.th/captiva")] completedExtractedDataRequest completedExtractedDataRequest) {
            object[] results = this.Invoke("completedExtractedData", new object[] {
                        completedExtractedDataRequest});
            return ((completedExtractedDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void completedExtractedDataAsync(completedExtractedDataRequest completedExtractedDataRequest) {
            this.completedExtractedDataAsync(completedExtractedDataRequest, null);
        }
        
        /// <remarks/>
        public void completedExtractedDataAsync(completedExtractedDataRequest completedExtractedDataRequest, object userState) {
            if ((this.completedExtractedDataOperationCompleted == null)) {
                this.completedExtractedDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OncompletedExtractedDataOperationCompleted);
            }
            this.InvokeAsync("completedExtractedData", new object[] {
                        completedExtractedDataRequest}, this.completedExtractedDataOperationCompleted, userState);
        }
        
        private void OncompletedExtractedDataOperationCompleted(object arg) {
            if ((this.completedExtractedDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.completedExtractedDataCompleted(this, new completedExtractedDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("poppulateDataResponse", Namespace="http://document.fwd.co.th/captiva")]
        public poppulateDataResponse poppulateData([System.Xml.Serialization.XmlElementAttribute(Namespace="http://document.fwd.co.th/captiva")] poppulateDataRequest poppulateDataRequest) {
            object[] results = this.Invoke("poppulateData", new object[] {
                        poppulateDataRequest});
            return ((poppulateDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void poppulateDataAsync(poppulateDataRequest poppulateDataRequest) {
            this.poppulateDataAsync(poppulateDataRequest, null);
        }
        
        /// <remarks/>
        public void poppulateDataAsync(poppulateDataRequest poppulateDataRequest, object userState) {
            if ((this.poppulateDataOperationCompleted == null)) {
                this.poppulateDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpoppulateDataOperationCompleted);
            }
            this.InvokeAsync("poppulateData", new object[] {
                        poppulateDataRequest}, this.poppulateDataOperationCompleted, userState);
        }
        
        private void OnpoppulateDataOperationCompleted(object arg) {
            if ((this.poppulateDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.poppulateDataCompleted(this, new poppulateDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("generateSubmissionNumberResponse", Namespace="http://document.fwd.co.th/captiva")]
        public generateSubmissionNumberResponse generateSubmissionNumber([System.Xml.Serialization.XmlElementAttribute(Namespace="http://document.fwd.co.th/captiva")] generateSubmissionNumberRequest generateSubmissionNumberRequest) {
            object[] results = this.Invoke("generateSubmissionNumber", new object[] {
                        generateSubmissionNumberRequest});
            return ((generateSubmissionNumberResponse)(results[0]));
        }
        
        /// <remarks/>
        public void generateSubmissionNumberAsync(generateSubmissionNumberRequest generateSubmissionNumberRequest) {
            this.generateSubmissionNumberAsync(generateSubmissionNumberRequest, null);
        }
        
        /// <remarks/>
        public void generateSubmissionNumberAsync(generateSubmissionNumberRequest generateSubmissionNumberRequest, object userState) {
            if ((this.generateSubmissionNumberOperationCompleted == null)) {
                this.generateSubmissionNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerateSubmissionNumberOperationCompleted);
            }
            this.InvokeAsync("generateSubmissionNumber", new object[] {
                        generateSubmissionNumberRequest}, this.generateSubmissionNumberOperationCompleted, userState);
        }
        
        private void OngenerateSubmissionNumberOperationCompleted(object arg) {
            if ((this.generateSubmissionNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generateSubmissionNumberCompleted(this, new generateSubmissionNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://document.fwd.co.th/captiva")]
    public partial class uploadDocumentRequest {
        
        private document documentField;
        
        /// <remarks/>
        public document document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://document.fwd.co.th/captiva")]
    public partial class document {
        
        private string policyNumberField;
        
        private string documentIdField;
        
        private string idCardNumberField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string referenceNumberField;
        
        private string processTypeField;
        
        private string submissionNumberField;
        
        private string scanBatchNumberField;
        
        private string sourceField;
        
        private string boxNumberField;
        
        private byte[] fileContentField;
        
        private string fileExtensionField;
        
        private string nodeIdField;
        
        /// <remarks/>
        public string policyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
            }
        }
        
        /// <remarks/>
        public string documentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        public string idCardNumber {
            get {
                return this.idCardNumberField;
            }
            set {
                this.idCardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string processType {
            get {
                return this.processTypeField;
            }
            set {
                this.processTypeField = value;
            }
        }
        
        /// <remarks/>
        public string submissionNumber {
            get {
                return this.submissionNumberField;
            }
            set {
                this.submissionNumberField = value;
            }
        }
        
        /// <remarks/>
        public string scanBatchNumber {
            get {
                return this.scanBatchNumberField;
            }
            set {
                this.scanBatchNumberField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string boxNumber {
            get {
                return this.boxNumberField;
            }
            set {
                this.boxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
            }
        }
        
        /// <remarks/>
        public string fileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        public string nodeId {
            get {
                return this.nodeIdField;
            }
            set {
                this.nodeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://document.fwd.co.th/captiva")]
    public partial class uploadDocumentResponse {
        
        private string nodeIdField;
        
        private string documentIdField;
        
        private string categoryField;
        
        private string formNameField;
        
        private string statusField;
        
        private string messageField;
        
        /// <remarks/>
        public string nodeId {
            get {
                return this.nodeIdField;
            }
            set {
                this.nodeIdField = value;
            }
        }
        
        /// <remarks/>
        public string documentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string formName {
            get {
                return this.formNameField;
            }
            set {
                this.formNameField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://document.fwd.co.th/captiva")]
    public partial class completedExtractedDataRequest {
        
        private string submissionNumberField;
        
        /// <remarks/>
        public string submissionNumber {
            get {
                return this.submissionNumberField;
            }
            set {
                this.submissionNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://document.fwd.co.th/captiva")]
    public partial class completedExtractedDataResponse {
        
        private string statusField;
        
        private string messageField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://document.fwd.co.th/captiva")]
    public partial class poppulateDataRequest {
        
        private string identittyNoField;
        
        /// <remarks/>
        public string identittyNo {
            get {
                return this.identittyNoField;
            }
            set {
                this.identittyNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://document.fwd.co.th/captiva")]
    public partial class poppulateDataResponse {
        
        private string identittyNoField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string statusField;
        
        private string messageField;
        
        /// <remarks/>
        public string identittyNo {
            get {
                return this.identittyNoField;
            }
            set {
                this.identittyNoField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://document.fwd.co.th/captiva")]
    public partial class generateSubmissionNumberRequest {
        
        private string requestIdField;
        
        /// <remarks/>
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://document.fwd.co.th/captiva")]
    public partial class generateSubmissionNumberResponse {
        
        private string submissionNumberField;
        
        private string statusField;
        
        private string messageField;
        
        /// <remarks/>
        public string submissionNumber {
            get {
                return this.submissionNumberField;
            }
            set {
                this.submissionNumberField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void uploadDocumentCompletedEventHandler(object sender, uploadDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public uploadDocumentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((uploadDocumentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void completedExtractedDataCompletedEventHandler(object sender, completedExtractedDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class completedExtractedDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal completedExtractedDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public completedExtractedDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((completedExtractedDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void poppulateDataCompletedEventHandler(object sender, poppulateDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class poppulateDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal poppulateDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public poppulateDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((poppulateDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void generateSubmissionNumberCompletedEventHandler(object sender, generateSubmissionNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generateSubmissionNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generateSubmissionNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public generateSubmissionNumberResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((generateSubmissionNumberResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591